#!/bin/bash

echo "🔧 Applying all fixes..."
echo "========================"

echo "1. Updating Firestore rules..."
echo "   Go to: https://console.firebase.google.com/project/whisper-chat-live/firestore/rules"
echo "   Paste:"
echo "   rules_version = '2';"
echo "   service cloud.firestore {"
echo "     match /databases/{database}/documents {"
echo "       match /{document=**} {"
echo "         allow read, write: if request.auth != null;"
echo "       }"
echo "     }"
echo "   }"
echo "   Click PUBLISH and wait 30 seconds"
echo ""
echo "2. Clearing browser cache..."
echo "   Press Ctrl+Shift+Delete, check 'Cached images and files', click 'Clear data'"
echo ""
echo "3. Fix complete!"
echo ""
echo "📱 Test your dashboard: https://pariisway.github.io/whisperme/dashboard.html"
echo "👤 Test profile page: https://pariisway.github.io/whisperme/profile.html"
