#!/bin/bash

echo "🧪 TESTING YOUR SITE"
echo "===================="
echo ""
echo "Open these links in your browser:"

echo ""
echo "1. Homepage (Main site):"
echo "   https://pariisway.github.io/whisperme/"
echo ""
echo "2. Dashboard:"
echo "   https://pariisway.github.io/whisperme/dashboard.html"
echo ""
echo "3. Payment Page:"
echo "   https://pariisway.github.io/whisperme/payment.html"
echo ""
echo "✅ What to check:"
echo "   - Homepage loads without errors"
echo "   - Text shows '5-minute' not '15-minute'"
echo "   - Dashboard 'Find Whispers' button works"
echo "   - No JavaScript errors in console (F12 → Console)"
echo ""
echo "🔄 If you see any issues, clear browser cache:"
echo "   Press Ctrl+Shift+Delete"
echo "   Check 'Cached images and files'"
echo "   Click 'Clear data'"
echo ""
echo "🎉 Your site should be back to normal now!"
